### ISSUE TITLE
ci: Publish to DockerHub doesn't use cached artifacts

### ISSUE THREAD

**Issue by stephan83** [stratumn/go-core#479]
The logs https://stratumn.semaphoreci.com/jobs/48607f67-2a3e-4da1-b47e-56b2621f7abc show that `make docker_images` rebuilds the binaries even though `dist` was restored from the cache.

I think it might have something to do with the timestamps. Maybe `make` thinks the binaries are outdated?

**Comment by alexppxela** [comment]
If you are sure that your dist binaries are up to date, `touch` all dist binaries after restoring it before calling the ocker_images rule.
