### ISSUE TITLE
Add migration from protobuf to json

### ISSUE THREAD

**Issue by jeremie-stratumn** [stratumn/go-core#512]
user should have a way to opt in / out protobuf / json serialization. The migration should convert all existing links + evidences from one serialization to the other.

**Comment by t-bast** [comment]
We simplified that, there won't be an option to store protobuf-encoded bytes in the DB, only JSON. Once we have the new migration tool we'll be able to write the migration for the current DBs.

**Comment by t-bast** [comment]
This blocked until we have the new migration tool available in Trace.

**Comment by t-bast** [comment]
Done.
